CREATE TABLE "StammdatenV1" (
    "id" TEXT NOT NULL,
    "unternehmensname" TEXT,
    "inhaber" TEXT,
    "website" TEXT,
    "strasse" TEXT,
    "plz" TEXT,
    "ort" TEXT,
    "land" TEXT,
    "email" TEXT,
    "telefon" TEXT,
    "whatsapp" TEXT,
    "kontaktHinweis" TEXT,
    "buerozeiten" JSONB,
    "instagramUrl" TEXT,
    "facebookUrl" TEXT,
    "tiktokUrl" TEXT,
    "impressumName" TEXT,
    "umsatzsteuerId" TEXT,
    "steuernummer" TEXT,
    "amtsgericht" TEXT,
    "registerangabe" TEXT,
    "bankName" TEXT,
    "bankKontoinhaber" TEXT,
    "bankKonto" TEXT,
    "bankBlz" TEXT,
    "bankIban" TEXT,
    "bankBic" TEXT,
    "geaendertAm" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "StammdatenV1_pkey" PRIMARY KEY ("id")
);
