import type { Metadata } from "next";
import Link from "next/link";
import type { Prisma } from "@/generated/prisma/client";

import { requireActiveAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { saveInternalNote, setContactRequestStatus } from "./actions";

export const metadata: Metadata = { title: "Kontaktanfragen | Admin | Huus & Meer", robots: { index: false, follow: false } };
const labels = { NEU: "Neu", IN_BEARBEITUNG: "In Bearbeitung", ERLEDIGT: "Erledigt" } as const;
type Status = keyof typeof labels;
const contactInclude = { anfragetyp: true, hausbootAngebot: { select: { titel: true } }, liegeplatzAngebot: { select: { titel: true } }, service: { select: { titel: true, serviceKategorie: { select: { name: true } } } }, stellenangebot: { select: { titel: true } }, interneNotizen: { orderBy: { erstelltAm: "desc" as const } } } satisfies Prisma.KontaktanfrageInclude;
type ContactRequest = Prisma.KontaktanfrageGetPayload<{ include: typeof contactInclude }>;
type Reference = { hausbootAngebot: { titel: string | null } | null; liegeplatzAngebot: { titel: string | null } | null; service: { titel: string; serviceKategorie: { name: string } } | null; serviceKategorieName: string | null; stellenangebot: { titel: string | null } | null };
const date = (value: Date) => new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" }).format(value);
function reference(item: Reference) { if (item.hausbootAngebot) return `Hausboot: ${item.hausbootAngebot.titel ?? "Ohne Titel"}`; if (item.liegeplatzAngebot) return `Liegeplatz: ${item.liegeplatzAngebot.titel ?? "Ohne Titel"}`; if (item.service) return `Service: ${item.service.serviceKategorie.name} – ${item.service.titel}`; if (item.serviceKategorieName) return `Service-Kategorie: ${item.serviceKategorieName}`; if (item.stellenangebot) return `Stellenangebot: ${item.stellenangebot.titel ?? "Ohne Titel"}`; return "Allgemeine Anfrage"; }

export default async function Page({ searchParams }: { searchParams: Promise<{ anfrage?: string; hinweis?: string; status?: string }> }) {
  await requireActiveAdmin(); const query = await searchParams; const status = (Object.keys(labels) as Status[]).includes(query.status as Status) ? query.status as Status : null;
  const [items, current] = await Promise.all([prisma.kontaktanfrage.findMany({ where: status ? { status } : undefined, include: contactInclude, orderBy: [{ status: "asc" }, { erstelltAm: "desc" }] }), query.anfrage ? prisma.kontaktanfrage.findUnique({ where: { id: query.anfrage }, include: contactInclude }) : null]);
  const overview = status ? `/admin/kontaktanfragen?status=${status}` : "/admin/kontaktanfragen";
  return <main className="min-h-dvh bg-mist p-4 sm:p-6 lg:p-8"><div className="mx-auto w-full max-w-[96rem]"><header className="rounded-2xl border border-mist-line bg-ice p-5 shadow-sm sm:p-7"><p className="text-sm font-semibold uppercase tracking-[.16em] text-brand">Huus & Meer · Verwaltung</p><h1 className="mt-2 text-3xl font-semibold">Kontaktanfragen</h1><p className="mt-2 text-sm text-ink/70">Neue Anfragen sind hervorgehoben. Serviceanfragen zeigen Kategorie und – falls ausgewählt – die konkrete Leistung.</p></header>{query.hinweis ? <p aria-live="polite" className="mt-4 rounded-xl bg-ice p-3 text-sm">{query.hinweis}</p> : null}{!current ? <Overview items={items} overview={overview} status={status} /> : <Detail current={current} />}</div></main>;
}

function Overview({ items, overview, status }: { items: ContactRequest[]; overview: string; status: Status | null }) { return <section className="mt-5 rounded-2xl border border-mist-line bg-ice p-5 shadow-sm sm:p-7"><nav aria-label="Kontaktanfragen filtern" className="mb-5 flex flex-wrap gap-2">{[[null, "Alle"], ["NEU", "Neu"], ["IN_BEARBEITUNG", "In Bearbeitung"], ["ERLEDIGT", "Erledigt"]].map(([value, label]) => <Link className={`min-h-11 rounded-xl px-4 py-2 text-sm font-semibold ${status === value ? "bg-brand text-ice" : "border border-mist-line text-brand"}`} href={value ? `/admin/kontaktanfragen?status=${value}` : overview} key={value ?? "alle"}>{label}</Link>)}</nav><div className="overflow-x-auto"><table className="w-full min-w-[54rem] text-left text-sm"><thead><tr className="border-b border-mist-line text-ink/65"><th className="pb-3">Name</th><th>E-Mail</th><th>Anfragetyp</th><th>Bezug</th><th>Status</th><th>Eingang</th><th>Aktion</th></tr></thead><tbody>{items.map((item) => <tr className={`border-b border-mist-line ${item.status === "NEU" ? "bg-brand/5" : ""}`} key={item.id}><td className="py-4 font-semibold">{item.name}</td><td>{item.email}</td><td>{item.anfragetyp.name}</td><td>{reference(item)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.status === "NEU" ? "bg-brand/10 text-brand" : "bg-mist text-ink/70"}`}>{labels[item.status]}</span></td><td>{date(item.erstelltAm)}</td><td><Link className="font-semibold text-brand" href={`/admin/kontaktanfragen?anfrage=${item.id}${status ? `&status=${status}` : ""}`}>Öffnen</Link></td></tr>)}{items.length === 0 ? <tr><td className="py-8 text-ink/70" colSpan={7}>Keine Kontaktanfragen in dieser Ansicht.</td></tr> : null}</tbody></table></div></section>; }

function Detail({ current }: { current: ContactRequest }) { return <section className="mt-5 rounded-2xl border border-mist-line bg-ice p-5 shadow-sm sm:p-7"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-brand">{labels[current.status]}</p><h2 className="mt-1 text-2xl font-semibold">Anfrage von {current.name}</h2><p className="mt-1 text-sm text-ink/70">Eingegangen am {date(current.erstelltAm)}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-xl bg-mist p-4"><h3 className="font-semibold">Kontaktdaten</h3><p className="mt-3 text-sm">{current.email}</p><p className="mt-2 text-sm">{current.telefon ?? "–"}</p></article><article className="rounded-xl bg-mist p-4"><h3 className="font-semibold">Anfragebezug</h3><p className="mt-3 text-sm">{current.anfragetyp.name}</p><p className="mt-2 text-sm text-ink/70">{reference(current)}</p></article><article className="rounded-xl bg-mist p-4 md:col-span-2"><h3 className="font-semibold">Nachricht</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{current.nachricht}</p></article></div><section className="mt-6 border-t border-mist-line pt-5"><h3 className="font-semibold">Status</h3><div className="mt-3 flex flex-wrap gap-3">{(Object.keys(labels) as Status[]).map((status) => <form action={setContactRequestStatus} key={status}><input name="id" type="hidden" value={current.id} /><input name="status" type="hidden" value={status} /><button className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${current.status === status ? "bg-brand text-ice" : "border border-mist-line"}`}>{labels[status]}</button></form>)}</div></section><section className="mt-6 border-t border-mist-line pt-5"><h3 className="font-semibold">Interne Notizen</h3><p className="mt-1 text-sm text-ink/65">Diese Notizen sind ausschließlich im Admin sichtbar.</p><div className="mt-4 space-y-3">{current.interneNotizen.map((note) => <form action={saveInternalNote} className="rounded-xl bg-mist p-3" key={note.id}><input name="id" type="hidden" value={note.id} /><input name="anfrageId" type="hidden" value={current.id} /><textarea className="min-h-20 w-full rounded-lg border border-mist-line bg-ice p-2 text-sm" defaultValue={note.inhalt} name="inhalt" /><div className="mt-2 flex items-center justify-between gap-3"><span className="text-xs text-ink/60">{date(note.erstelltAm)}</span><button className="text-sm font-semibold text-brand">Notiz speichern</button></div></form>)}<form action={saveInternalNote} className="rounded-xl border border-dashed border-mist-line p-3"><input name="anfrageId" type="hidden" value={current.id} /><label className="text-sm font-semibold">Neue interne Notiz<textarea className="mt-2 min-h-24 w-full rounded-lg border border-mist-line bg-ice p-2" name="inhalt" required /></label><button className="mt-3 min-h-11 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-ice">Notiz hinzufügen</button></form></div></section></section>; }
