import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import type { PublicMasterData } from "@/data/site";

const groups = [{ title: "Für Urlauber/innen", links: ["Finde Hausbooturlaube", "Urlauber A-Z", "Kurtaxe & Ostseecard"] }, { title: "Für Eigentümer/innen", links: ["Verkauf Liegeplätze", "Verkauf Hausboote", "Serviceleistungen"] }, { title: "Jobs & Kontakt", links: ["Stellenangebote", "Kontakt", "Impressum", "Datenschutzerklärung", "AGB", "Cookie-Settings"] }];
const emptyMasterData: PublicMasterData = { address: null, companyName: null, email: null, facebookUrl: null, instagramUrl: null, officeHours: null, phone: null, tiktokUrl: null };
const href = (link: string) => ({ Stellenangebote: "/stellenangebote", Kontakt: "/kontakt", Serviceleistungen: "/services", "Kurtaxe & Ostseecard": "/kurtaxe-ostseecard", "Finde Hausbooturlaube": "/suchen-und-buchen", "Urlauber A-Z": "/suchen-und-buchen", "Verkauf Liegeplätze": "/vermieten-und-verkaufen", "Verkauf Hausboote": "/vermieten-und-verkaufen", Impressum: "/impressum", Datenschutzerklärung: "/datenschutz", AGB: "/agb" }[link] ?? "#kontakt");

export function Footer({ masterData = emptyMasterData }: { masterData?: PublicMasterData }) {
  const socialLinks = [["instagram", "Instagram", masterData.instagramUrl], ["facebook", "Facebook", masterData.facebookUrl], ["tiktok", "TikTok", masterData.tiktokUrl]] as const;
  return <footer className="border-t border-footer-line bg-footer pb-12 pt-14" id="footer"><div className="container-page grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><div className="relative mb-5 h-11 w-40"><Image alt="Huus & Meer" className="object-contain object-left" fill sizes="160px" src="/assets/images/logo.png" /></div><p className="max-w-xs text-sm leading-relaxed text-ink/70">Persönliche Ferienzeit, zuverlässige Betreuung und beste Verbindungen an der Ostsee.</p><div className="mt-5 space-y-2 text-sm">{masterData.phone ? <a className="flex items-center gap-2 hover:text-brand" href={`tel:${masterData.phone.replaceAll(/[^+\d]/g, "")}`}><Icon className="h-4 w-4" name="phone" />{masterData.phone}</a> : null}{masterData.email ? <a className="flex items-center gap-2 hover:text-brand" href={`mailto:${masterData.email}`}><Icon className="h-4 w-4" name="mail" />{masterData.email}</a> : null}{masterData.address ? <p>{masterData.address}</p> : null}{masterData.officeHours ? <p>{masterData.officeHours}</p> : null}{socialLinks.some(([, , url]) => url) ? <div className="flex items-center gap-3 pt-2">{socialLinks.filter(([, , url]) => Boolean(url)).map(([icon, label, url]) => <a aria-label={label} href={url ?? undefined} key={icon} rel="noreferrer" target="_blank"><Icon className="h-4 w-4" name={icon} /></a>)}</div> : null}</div></div>{groups.map((group) => <div key={group.title}><h3 className="mb-4 font-semibold">{group.title}</h3><ul className="space-y-3 text-sm text-ink/70">{group.links.map((link) => <li key={link}><Link className="hover:text-brand" href={href(link)}>{link}</Link></li>)}</ul></div>)}</div><div className="container-page mt-12 flex flex-col gap-3 border-t border-footer-line pt-5 text-xs text-ink/65 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 {masterData.companyName ?? "Huus & Meer"}</span><div className="flex flex-wrap items-center gap-3"><span>Wir segeln mit der <a className="underline underline-offset-2" href="#">Kogge. Digitalagentur</a></span><Link aria-label="Zum Admin-Bereich" className="group inline-flex min-h-10 items-center gap-1.5 rounded-sm border border-footer-line px-3 py-2 font-semibold text-ink/65 transition-colors duration-150 hover:border-ink/35 hover:bg-ink/5 hover:text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-ink motion-reduce:transition-none" href="/admin"><Icon className="h-3.5 w-3.5 transition-transform duration-150 group-hover:-translate-y-px motion-reduce:transition-none motion-reduce:group-hover:translate-y-0" name="shield" /><span className="sm:hidden">Admin</span><span className="hidden sm:inline">Admin-Bereich</span></Link></div></div></footer>;
}
