"use server";
import { randomBytes, randomUUID } from "node:crypto";
import { hash, compare } from "bcryptjs";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireActiveAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
const path="/admin/einstellungen"; const val=(f:FormData,k:string)=>typeof f.get(k)==="string"?String(f.get(k)).trim():""; const email=(v:string)=>/^\S+@\S+\.\S+$/.test(v);
const done=(note:string,fields:string[]=[]):never=>{revalidatePath(path);redirect(`${path}?hinweis=${encodeURIComponent(note)}${fields.length?`&typ=fehler&felder=${encodeURIComponent(fields.join(","))}`:""}`)};
export type CreateAdminState={error:string|null;code:string|null;fieldErrors?:{name?:string;email?:string}};
export async function createAdmin(_state:CreateAdminState,f:FormData):Promise<CreateAdminState>{await requireActiveAdmin();const name=val(f,"name"),mail=val(f,"email").toLowerCase();const fieldErrors={...(!name?{name:"Dieses Feld ist erforderlich."}:{}),...(!email(mail)?{email:"Bitte gib eine gültige E-Mail-Adresse ein."}:{})};if(Object.keys(fieldErrors).length)return{error:"Bitte prüfe die markierten Felder.",code:null,fieldErrors};if(await prisma.adminBenutzer.findUnique({where:{email:mail}}))return{error:"Die E-Mail-Adresse wird bereits verwendet.",code:null,fieldErrors:{email:"Die E-Mail-Adresse wird bereits verwendet."}};const role=await prisma.adminRolle.upsert({where:{name:"Administrator"},update:{},create:{id:randomUUID(),name:"Administrator"}});const code=randomBytes(18).toString("base64url");await prisma.adminBenutzer.create({data:{id:randomUUID(),adminRolleId:role.id,name,email:mail,passwortHash:null,istAktiv:false,einrichtungscodeHash:await hash(code,12),einrichtungscodeLaeuftAb:new Date(Date.now()+1000*60*60*24*7)}});revalidatePath(path);return{error:null,code,fieldErrors:{}}}
export async function updateAdmin(f:FormData){const current=await requireActiveAdmin();const id=val(f,"id"),name=val(f,"name"),mail=val(f,"email").toLowerCase();const fields=[...(!name?["name"]:[]),...(!email(mail)?["email"]:[])];if(!id||id===current.id||fields.length)done("Bitte prüfe die markierten Felder.",fields);const found=await prisma.adminBenutzer.findUnique({where:{email:mail}});if(found&&found.id!==id)done("Die E-Mail-Adresse wird bereits verwendet.",["email"]);await prisma.adminBenutzer.update({where:{id},data:{name,email:mail}});done("Administrator gespeichert.")}
export async function toggleAdmin(f:FormData){const current=await requireActiveAdmin();const id=val(f,"id");if(!id||id===current.id)done("Der eigene Account kann nicht deaktiviert werden.");const target=await prisma.adminBenutzer.findUnique({where:{id}});if(!target)throw new Error("Administrator nicht gefunden.");if(target.istAktiv){const active=await prisma.adminBenutzer.count({where:{istAktiv:true}});if(active<=1)done("Der letzte aktive Administrator kann nicht deaktiviert werden.");}await prisma.adminBenutzer.update({where:{id},data:{istAktiv:!target.istAktiv}});done(target.istAktiv?"Administrator deaktiviert.":"Administrator aktiviert.")}
export async function updateOwnProfile(f:FormData){const current=await requireActiveAdmin();const name=val(f,"name"),mail=val(f,"email").toLowerCase();const fields=[...(!name?["name"]:[]),...(!email(mail)?["email"]:[])];if(fields.length)redirect(`/admin/mein-konto?hinweis=${encodeURIComponent("Bitte prüfe die markierten Felder.")}&typ=fehler&felder=${fields.join(",")}`);const found=await prisma.adminBenutzer.findUnique({where:{email:mail}});if(found&&found.id!==current.id)redirect(`/admin/mein-konto?hinweis=${encodeURIComponent("Die E-Mail-Adresse wird bereits verwendet.")}&typ=fehler&felder=email`);await prisma.adminBenutzer.update({where:{id:current.id},data:{name,email:mail}});revalidatePath("/admin/mein-konto");redirect("/admin/mein-konto?hinweis=Kontodaten gespeichert.")}
export async function changeOwnPassword(f:FormData){const current=await requireActiveAdmin();const old=val(f,"aktuellesPasswort"),next=val(f,"neuesPasswort"),admin=await prisma.adminBenutzer.findUnique({where:{id:current.id}});if(!admin?.passwortHash||!(await compare(old,admin.passwortHash))||next.length<12)redirect(`/admin/mein-konto?hinweis=${encodeURIComponent("Aktuelles Passwort oder neues Passwort ungültig (mindestens 12 Zeichen).")}&typ=fehler&felder=aktuellesPasswort,neuesPasswort`);await prisma.adminBenutzer.update({where:{id:current.id},data:{passwortHash:await hash(next,12),sitzungVersion:{increment:1}}});redirect("/admin/login?hinweis=Passwort geändert. Bitte melde dich erneut an.")}
