import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal-page";

export const metadata: Metadata = { title: "Datenschutzerklärung | Huus & Meer" };

const sections = [
  ["2. Hosting", "Wir hosten die Inhalte unserer Website bei All-Inkl. Anbieter ist die ALL-INKL.COM – Neue Medien Münnich, Inh. René Münnich, Hauptstraße 68, 02742 Friedersdorf. Die Verwendung von All-Inkl erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO; eine Einwilligung ist jederzeit widerrufbar."],
  ["Auftragsverarbeitung", "Wir haben einen Vertrag über Auftragsverarbeitung zur Nutzung des oben genannten Dienstes geschlossen. Dieser gewährleistet, dass personenbezogene Daten nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet werden."],
  ["3. Allgemeine Hinweise und Pflichtinformationen", "Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. Die Datenübertragung im Internet kann Sicherheitslücken aufweisen."],
  ["Hinweis zur verantwortlichen Stelle", "Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:\nOlga Kaul\nAm Soll 12\n23769 Fehmarn\nTelefon: +49 (0) 4372 8066594\nE-Mail: moin@huus-und-meer.de"],
  ["Speicherdauer", "Soweit innerhalb dieser Datenschutzerklärung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für die Datenverarbeitung entfällt. Gesetzliche Aufbewahrungsfristen bleiben unberührt."],
  ["Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung", "Sofern Sie eingewilligt haben, verarbeiten wir Ihre Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO. Für Vertragserfüllung, rechtliche Verpflichtungen und berechtigte Interessen gelten die jeweils einschlägigen Rechtsgrundlagen; eine Einwilligung ist jederzeit widerrufbar."],
  ["Empfänger von personenbezogenen Daten", "Wir geben personenbezogene Daten nur weiter, wenn dies zur Vertragserfüllung erforderlich, gesetzlich vorgeschrieben oder durch eine andere Rechtsgrundlage erlaubt ist. Bei Auftragsverarbeitern gilt ein gültiger Vertrag über Auftragsverarbeitung."],
  ["Widerruf Ihrer Einwilligung zur Datenverarbeitung", "Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung bleibt unberührt."],
  ["Widerspruchsrecht", "Wenn die Datenverarbeitung auf Grundlage von Art. 6 Abs. 1 lit. e oder f DSGVO erfolgt, haben Sie jederzeit das Recht, aus Gründen Ihrer besonderen Situation Widerspruch einzulegen. Bei Direktwerbung besteht ein jederzeitiges Widerspruchsrecht."],
  ["Beschwerderecht bei der zuständigen Aufsichtsbehörde", "Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde zu."],
  ["Recht auf Datenübertragbarkeit", "Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen."],
  ["Auskunft, Berichtigung und Löschung", "Sie haben jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten sowie auf Berichtigung oder Löschung im Rahmen der gesetzlichen Bestimmungen."],
  ["Recht auf Einschränkung der Verarbeitung", "Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, insbesondere bei bestrittenen Daten, unrechtmäßiger Verarbeitung oder eingelegtem Widerspruch."],
  ["SSL- bzw. TLS-Verschlüsselung", "Diese Seite nutzt aus Sicherheitsgründen eine SSL- bzw. TLS-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie am Wechsel von http:// zu https:// und am Schloss-Symbol im Browser."],
  ["4. Datenerfassung auf dieser Website", "Unsere Internetseiten verwenden Cookies. Session-Cookies werden nach Ende Ihres Besuchs gelöscht; permanente Cookies bleiben gespeichert, bis Sie sie löschen oder Ihr Browser sie entfernt."],
  ["Cookies", "Cookies können von uns oder von Drittunternehmen stammen. Notwendige Cookies dienen der technisch fehlerfreien Bereitstellung; weitere Cookies können zur Auswertung des Nutzerverhaltens oder zu Werbezwecken verwendet werden. Sie können Ihren Browser so einstellen, dass Cookies nur im Einzelfall erlaubt oder beim Schließen gelöscht werden."],
  ["Real Cookie Banner", "Unsere Website nutzt die Consent-Technologie von Real Cookie Banner, um Einwilligungen zu dokumentieren. Die Technologie ist lokal installiert; die erfassten Daten werden bis zur Löschung oder zum Wegfall des Zwecks gespeichert."],
  ["Server-Log-Dateien", "Der Provider erhebt automatisch Server-Log-Dateien wie Browsertyp, Betriebssystem, Referrer URL, Hostname, Uhrzeit der Serveranfrage und IP-Adresse. Eine Zusammenführung mit anderen Datenquellen erfolgt nicht."],
  ["Kontaktformular", "Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben zur Bearbeitung der Anfrage und für Anschlussfragen gespeichert. Die Daten verbleiben bis zur Löschung oder zum Wegfall des Zwecks bei uns; gesetzliche Aufbewahrungsfristen bleiben unberührt."],
  ["Anfrage per E-Mail, Telefon oder Telefax", "Bei Kontaktaufnahme per E-Mail, Telefon oder Telefax wird Ihre Anfrage inklusive personenbezogener Daten zur Bearbeitung gespeichert und verarbeitet. Die Daten werden gelöscht, sobald der Zweck entfällt oder Sie die Löschung verlangen, soweit keine gesetzlichen Pflichten entgegenstehen."],
  ["5. Analyse-Tools und Werbung", "Beim Besuch dieser Website kann Ihr Surf-Verhalten statistisch ausgewertet werden. Detaillierte Informationen zu den eingesetzten Analyseprogrammen finden Sie in den folgenden Abschnitten."],
  ["Google Analytics", "Diese Website nutzt Funktionen des Webanalysedienstes Google Analytics, Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Die Nutzung erfolgt auf Grundlage Ihrer Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG; diese ist jederzeit widerrufbar."],
  ["IP-Anonymisierung", "Die Google-Analytics-IP-Anonymisierung ist aktiviert. Die IP-Adresse wird innerhalb der EU oder des EWR vor der Übermittlung in die USA gekürzt."],
  ["Browser Plugin", "Sie können die Erfassung und Verarbeitung Ihrer Daten durch Google verhindern, indem Sie das Browser-Plugin unter https://tools.google.com/dlpage/gaoptout?hl=de herunterladen und installieren."],
  ["Auftragsverarbeitung bei Google Analytics", "Wir haben mit Google einen Vertrag zur Auftragsverarbeitung abgeschlossen und setzen die Vorgaben der deutschen Datenschutzbehörden bei der Nutzung von Google Analytics um."],
] as const;

export default function DatenschutzPage() {
  return <LegalPage eyebrow="RECHTLICHES" title="Datenschutzerklärung"><LegalSection title="1. Datenschutz auf einen Blick"><h3 className="text-xl font-bold text-ink">Allgemeine Hinweise</h3><p>Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können.</p><h3 className="pt-4 text-xl font-bold text-ink">Datenerfassung auf dieser Website</h3><h4 className="pt-2 text-lg font-semibold text-ink">Wer ist verantwortlich für die Datenerfassung auf dieser Website?</h4><p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber.</p><h4 className="pt-2 text-lg font-semibold text-ink">Wie erfassen wir Ihre Daten?</h4><p>Ihre Daten werden dadurch erhoben, dass Sie uns diese mitteilen, etwa in einem Kontaktformular. Andere Daten werden automatisch oder nach Ihrer Einwilligung durch unsere IT-Systeme erfasst.</p><h4 className="pt-2 text-lg font-semibold text-ink">Wofür nutzen wir Ihre Daten?</h4><p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden.</p><h4 className="pt-2 text-lg font-semibold text-ink">Welche Rechte haben Sie bezüglich Ihrer Daten?</h4><p>Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Widerruf Ihrer Einwilligung sowie ein Beschwerderecht bei der zuständigen Aufsichtsbehörde.</p></LegalSection>{sections.map(([title, text]) => <LegalSection key={title} title={title}><p className="whitespace-pre-line break-words">{text}</p>{title === "Cookies" ? <ul className="list-disc pl-6"><li>First-Party- und Third-Party-Cookies können eingesetzt werden.</li><li>Notwendige Cookies dienen der technisch fehlerfreien Bereitstellung.</li></ul> : null}</LegalSection>)}</LegalPage>;
}
