import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { connection } from "next/server";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { publicMasterDataFrom } from "@/lib/public-master-data";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Für Eigentümer/innen | Huus & Meer", description: "Hausboote und Liegeplätze an der Ostsee mit Huus & Meer verkaufen." };
const pageSize = 6;
const currency = (value: { toString(): string } | null) => value ? new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(value.toString())) : null;
const currentPage = (value: string | undefined) => Math.max(1, Number.isSafeInteger(Number(value)) ? Number(value) : 1);

export default async function OwnerOverviewPage({ searchParams }: { searchParams: Promise<{ hausbooteSeite?: string; liegeplaetzeSeite?: string }> }) {
  await connection();
  const query = await searchParams;
  const houseboatPage = currentPage(query.hausbooteSeite);
  const berthPage = currentPage(query.liegeplaetzeSeite);
  const visible = { status: "VEROEFFENTLICHT" } as const;
  const [houseboatCount, berthCount, houseboats, berths, masterData] = await Promise.all([
    prisma.hausbootAngebot.count({ where: visible }),
    prisma.liegeplatzAngebot.count({ where: visible }),
    prisma.hausbootAngebot.findMany({ where: visible, select: { slug: true, titel: true, beschreibung: true, standort: true, preis: true, baujahr: true, anzahlSchlafplaetze: true, wohnflaeche: true, bilder: { orderBy: [{ istTitelbild: "desc" }, { reihenfolge: "asc" }], take: 1 } }, orderBy: [{ hervorgehoben: "desc" }, { geaendertAm: "desc" }], skip: (houseboatPage - 1) * pageSize, take: pageSize }),
    prisma.liegeplatzAngebot.findMany({ where: visible, select: { slug: true, titel: true, beschreibung: true, standort: true, preis: true, laenge: true, breite: true, moeglicheBootsgroesse: true, bilder: { orderBy: [{ istTitelbild: "desc" }, { reihenfolge: "asc" }], take: 1 } }, orderBy: [{ hervorgehoben: "desc" }, { geaendertAm: "desc" }], skip: (berthPage - 1) * pageSize, take: pageSize }),
    prisma.stammdatenV1.findUnique({ where: { id: "zentral" } }),
  ]);
  const master = publicMasterDataFrom(masterData);
  return <><Header masterData={master} /><main className="bg-mist"><section className="container-page py-[clamp(4rem,8vw,8rem)]"><h1 className="max-w-4xl text-[clamp(2.6rem,6vw,5rem)] font-semibold leading-[.98] tracking-tight text-brand">Für Eigentümer/innen</h1><h2 className="mt-6 max-w-3xl text-[clamp(1.5rem,3vw,2.4rem)] font-semibold leading-tight">Alles rund um den Verkauf deines Hausboots und Liegeplatzes</h2><p className="mt-5 max-w-2xl leading-relaxed text-ink/70">Huus & Meer begleitet dich mit Marktkenntnis, Sorgfalt und einem starken Netzwerk beim Verkauf und bei der Vermittlung an der Ostseeküste.</p><ListingSection id="hausboote" title="Hausboote zum Verkauf" emptyTitle="Aktuell keine Hausboote zum Verkauf" emptyText="Sobald ein Hausboot verfügbar ist, findest du es hier." currentPage={houseboatPage} otherPage={berthPage} pageCount={Math.ceil(houseboatCount / pageSize)} pageKey="hausbooteSeite" items={houseboats.map((item) => ({ ...item, href: `/eigentuemer/verkauf/hausboote/${item.slug}`, facts: [item.standort, item.wohnflaeche, item.anzahlSchlafplaetze ? `${item.anzahlSchlafplaetze} Schlafplätze` : null, item.baujahr ? `Baujahr ${item.baujahr}` : null], price: currency(item.preis) }))} /><ListingSection id="liegeplaetze" title="Liegeplätze zum Verkauf" emptyTitle="Aktuell keine Liegeplätze zum Verkauf" emptyText="Sobald ein Liegeplatz verfügbar ist, findest du ihn hier." currentPage={berthPage} otherPage={houseboatPage} pageCount={Math.ceil(berthCount / pageSize)} pageKey="liegeplaetzeSeite" items={berths.map((item) => ({ ...item, href: `/eigentuemer/verkauf/liegeplaetze/${item.slug}`, facts: [item.standort, [item.laenge, item.breite].filter(Boolean).join(" × ") || null, item.moeglicheBootsgroesse], price: currency(item.preis) }))} /></section></main><Footer masterData={master} /></>;
}
type Item = { slug: string; titel: string | null; beschreibung: string | null; href: string; price: string | null; facts: (string | null)[]; bilder: { id: string; bildReferenz: string; altText: string | null }[] };
type ListingSectionProps = { id: string; title: string; emptyTitle: string; emptyText: string; items: Item[]; pageKey: "hausbooteSeite" | "liegeplaetzeSeite"; currentPage: number; otherPage: number; pageCount: number };
function ListingSection({ id, title, emptyTitle, emptyText, items, pageKey, currentPage, otherPage, pageCount }: ListingSectionProps) { return <section className="mt-[clamp(4rem,9vw,8rem)]" id={id}><h2 className="text-[clamp(2rem,4vw,3.5rem)] font-semibold leading-tight tracking-tight">{title}</h2>{items.length ? <><div className="mt-7 grid gap-5 lg:grid-cols-2">{items.map((item) => <article className="overflow-hidden rounded-2xl border border-mist-line bg-ice" key={item.slug}><div className="grid min-w-0 sm:grid-cols-[minmax(14rem,.85fr)_minmax(0,1fr)]">{item.bilder[0] ? <div className="relative min-h-56"><Image alt={item.bilder[0].altText ?? item.titel ?? title} className="object-cover" fill sizes="(max-width: 639px) calc(100vw - 2.5rem), (max-width: 1023px) 45vw, 25vw" src={item.bilder[0].bildReferenz} unoptimized /></div> : null}<div className="flex min-w-0 flex-col p-5 sm:p-6"><h3 className="text-2xl font-semibold">{item.titel}</h3>{item.beschreibung ? <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-ink/70">{item.beschreibung}</p> : null}{item.price ? <p className="mt-5 text-sm font-semibold text-brand">{item.price}</p> : null}{item.facts.some(Boolean) ? <p className="mt-2 text-sm text-ink/70">{item.facts.filter(Boolean).join(" · ")}</p> : null}<Link className="mt-6 inline-flex min-h-12 w-fit items-center rounded-[.2rem] border border-brand bg-brand px-5 py-3 text-sm font-bold text-ice transition hover:bg-ice hover:text-ink" href={item.href}>Mehr erfahren</Link></div></div></article>)}</div><ListingPagination currentPage={currentPage} otherPage={otherPage} pageCount={pageCount} pageKey={pageKey} sectionId={id} /></> : <div className="mt-7 rounded-2xl border border-mist-line bg-ice p-[clamp(1.5rem,4vw,3rem)]"><h3 className="text-2xl font-semibold">{emptyTitle}</h3><p className="mt-3 max-w-xl leading-relaxed text-ink/70">{emptyText}</p></div>}</section>; }
function ListingPagination({ currentPage, otherPage, pageCount, pageKey, sectionId }: { currentPage: number; otherPage: number; pageCount: number; pageKey: "hausbooteSeite" | "liegeplaetzeSeite"; sectionId: string }) { if (pageCount < 2) return null; const otherKey = pageKey === "hausbooteSeite" ? "liegeplaetzeSeite" : "hausbooteSeite"; const href = (page: number) => `/eigentuemer?${pageKey}=${page}&${otherKey}=${otherPage}#${sectionId}`; return <nav aria-label={`${sectionId} Seiten`} className="mt-8 flex flex-wrap items-center justify-center gap-2"><Link aria-disabled={currentPage === 1} className={`inline-flex min-h-11 items-center rounded-[.2rem] border px-4 text-sm font-bold ${currentPage === 1 ? "pointer-events-none border-mist-line text-ink/40" : "border-brand text-brand hover:bg-ice"}`} href={href(currentPage - 1)}>← Zurück</Link>{Array.from({ length: pageCount }, (_, index) => index + 1).map((page) => <Link aria-current={page === currentPage ? "page" : undefined} className={`grid h-11 min-w-11 place-items-center rounded-[.2rem] border text-sm font-bold ${page === currentPage ? "border-brand bg-brand text-ice" : "border-mist-line text-brand hover:bg-ice"}`} href={href(page)} key={page}>{page}</Link>)}<Link aria-disabled={currentPage === pageCount} className={`inline-flex min-h-11 items-center rounded-[.2rem] border px-4 text-sm font-bold ${currentPage === pageCount ? "pointer-events-none border-mist-line text-ink/40" : "border-brand text-brand hover:bg-ice"}`} href={href(currentPage + 1)}>Weiter →</Link></nav>; }
