import Link from "next/link";
import { SaleDetailActions } from "@/components/sale-detail-actions";
import { SaleGallery } from "@/components/sale-gallery";

type Detail = { label: string; value: string | null };
type SaleObject = { id: string; titel: string | null; beschreibung: string | null; preis: { toString(): string } | null; preisHinweis: string | null; images: { id: string; bildReferenz: string; altText: string | null }[]; primaryDetails: Detail[]; technicalDetails: Detail[]; equipment?: unknown };
const price = (value: { toString(): string } | null) => value ? new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(value.toString())) : null;
const valuesFromEquipment = (equipment: unknown) => equipment && typeof equipment === "object" && !Array.isArray(equipment) ? Object.entries(equipment as Record<string, unknown>).flatMap(([label, value]) => typeof value === "string" && value.trim() ? [{ label, value: value.trim() }] : []) : [];
const equipmentLabel = (key: string) => ({ heizung: "Heizung", faekalientankinhalt: "Fäkalientankinhalt", eingangstuerbreite: "Eingangstürbreite", terrassentuer: "Terrassentür", innentueren: "Innentüren", hauskonstruktion: "Hauskonstruktion", sicherungskasten: "Sicherungskasten", boiler: "Boiler", elektrik: "Elektrik", feuerloescher: "Feuerlöscher", fernseher: "Fernseher", herd: "Herd", kueche: "Küche", wohnzimmer: "Wohnzimmer", oberdeck: "Oberdeck" }[key] ?? key);

export function SaleDetailPage({ object, objectKind, inquiryTypes }: { object: SaleObject; objectKind: "HAUSBOOT" | "LIEGEPLATZ"; inquiryTypes: { id: string; name: string }[] }) {
  const noun = objectKind === "HAUSBOOT" ? "Hausboot" : "Liegeplatz";
  const primary = [{ label: "Preis", value: price(object.preis) }, { label: "Preishinweis", value: object.preisHinweis }, ...object.primaryDetails].filter((item) => Boolean(item.value));
  const technical = object.technicalDetails.filter((item) => Boolean(item.value));
  const equipment = valuesFromEquipment(object.equipment);
  return <article className="container-page py-[clamp(3rem,7vw,7rem)]"><Link className="text-sm font-semibold text-brand" href="/eigentuemer">← Alle Verkaufsobjekte</Link><h1 className="mt-8 max-w-4xl text-[clamp(2.5rem,5.5vw,5rem)] font-semibold leading-[.98] tracking-tight">{noun} „{object.titel}“</h1><SaleGallery images={object.images} title={object.titel ?? noun} />{primary.length ? <DetailSection details={primary} title="Die wichtigsten Daten" /> : null}{technical.length ? <DetailSection details={technical} title="Technische Daten" /> : null}{equipment.length ? <section className="mt-10"><h2 className="text-[clamp(1.8rem,3vw,2.6rem)] font-semibold">Ausstattung</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{equipment.map((item) => <div className="rounded-xl border border-mist-line bg-ice p-4" key={item.label}><dt className="text-sm font-semibold text-ink/60">{equipmentLabel(item.label)}</dt><dd className="mt-1 leading-relaxed">{item.value}</dd></div>)}</dl></section> : null}{object.beschreibung ? <section className="mt-10 max-w-4xl" aria-labelledby="sale-about-title"><h2 className="text-[clamp(1.8rem,3vw,2.6rem)] font-semibold" id="sale-about-title">Beschreibung</h2><p className="mt-5 whitespace-pre-wrap leading-relaxed text-ink/75">{object.beschreibung}</p></section> : null}<SaleDetailActions inquiryTypes={inquiryTypes} objectId={object.id} objectKind={objectKind} /></article>;
}
function DetailSection({ details, title }: { details: Detail[]; title: string }) { return <section className="mt-10" aria-label={title}><h2 className="text-[clamp(1.8rem,3vw,2.6rem)] font-semibold">{title}</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{details.map((item) => <div className="rounded-xl border border-mist-line bg-ice p-4" key={item.label}><dt className="text-sm font-semibold text-ink/60">{item.label}</dt><dd className="mt-1 text-lg font-semibold leading-snug">{item.value}</dd></div>)}</dl></section>; }
