import type { Metadata } from "next";
import Link from "next/link";
import { connection } from "next/server";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { SectionLabel } from "@/components/ui/section-label";
import { publicMasterDataFrom } from "@/lib/public-master-data";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Stellenangebote | Huus & Meer", description: "Aktuelle Stellenangebote bei Huus & Meer auf Fehmarn und an der Ostsee." };
export default async function JobOverviewPage() { await connection(); const [jobs, masterData] = await Promise.all([prisma.stellenangebot.findMany({ where: { status: "VEROEFFENTLICHT" }, include: { arbeitsorte: { orderBy: { reihenfolge: "asc" } } }, orderBy: { titel: "asc" } }), prisma.stammdatenV1.findUnique({ where: { id: "zentral" } })]); const master = publicMasterDataFrom(masterData); return <><Header masterData={master} /><main className="bg-sand"><section className="container-page py-[clamp(4rem,8vw,8rem)]"><SectionLabel>STELLENANGEBOTE</SectionLabel><h1 className="mt-3 max-w-4xl text-[clamp(2.6rem,6vw,5rem)] font-semibold leading-[.98] tracking-tight">Arbeiten, wo andere Urlaub machen.</h1><p className="mt-5 max-w-2xl leading-relaxed text-ink/70">Entdecke unsere aktuellen Möglichkeiten und werde Teil von Huus & Meer.</p>{jobs.length === 0 ? <section className="mt-10 rounded-2xl border border-sand-line bg-linen p-[clamp(1.5rem,4vw,3rem)]"><h2 className="text-2xl font-semibold">Aktuell keine offenen Stellen</h2><p className="mt-3 max-w-xl leading-relaxed text-ink/70">Schau gern zu einem späteren Zeitpunkt wieder vorbei – wir freuen uns immer über Menschen, die unsere Begeisterung für die Ostsee teilen.</p></section> : <div className={`mt-10 grid gap-5 ${jobs.length > 1 ? "lg:grid-cols-2" : "max-w-4xl"}`}>{jobs.map((job) => <article className="rounded-2xl border border-sand-line bg-linen p-6 sm:p-8" key={job.id}><p className="text-sm font-semibold uppercase tracking-[.16em] text-red">{job.arbeitspensum ?? "Stellenangebot"}</p><h2 className="mt-3 text-3xl font-semibold">{job.titel}</h2><p className="mt-4 line-clamp-3 leading-relaxed text-ink/70">{job.beschreibung}</p><dl className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-ink/70"><div><dt className="sr-only">Arbeitsort</dt><dd>{job.arbeitsorte.map((item) => item.ort).join(", ") || "Arbeitsort nach Vereinbarung"}</dd></div>{job.arbeitszeiten ? <div><dt className="sr-only">Arbeitszeiten</dt><dd>{job.arbeitszeiten}</dd></div> : null}</dl><Link className="mt-7 inline-flex min-h-12 items-center rounded-[0.2rem] border border-red bg-red px-5 py-3 text-sm font-bold text-linen transition hover:bg-sand hover:text-ink" href={`/stellenangebote/${job.id}`}>Mehr erfahren</Link></article>)}</div>}</section></main><Footer masterData={master} /></>; }
